### ISSUE TITLE
Milestone 3 Peer Feedback (Sasha)

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/bc_election_turnout#60]
I really enjoyed reviewing your project! You have chosen an interesting question and your report is easy to follow and well written. 

## Documentation
*Yes it is great!*
- Code was appropriately documented, README instructions were pretty clear, and the EDA gave a nice walk through of the important aspects of the data.  
- I have a few suggestions in the suggestions section, but overall the project is well documented and clear for an outsider to understand. 

## Code
*Yes it is great!*
- The code is simple (in a good way!), functional, and easy to read. 

## Analysis and reasoning
*Yes it is great!*
- Seemed reasonable! I liked the discussion at the end about what it all means, it ties everything together nicely.

## Communication
*Yes it is great!*
- The report is very clear and easy to follow. 
- As someone with no domain knowledge I am curious about how you chose your alpha value?
- Not sure if I just missed it, but what does the "Any problems" column for in the report tables represent? 

## Suggestions
NOTE: I got pretty nit-picky with these, so feel free to not address anything you feel won't improve the end product 
- A link to the EDA in GitHub when you reference it in your report would be handy!
- The data tables in the report look a bit fuzzy, perhaps changing the format from jpg to png or svg would improve the image quality. 
- For the figure "The more competitive the race, the greater the turnout" in your README and report it might be easier to read with colours rather than shapes. 
- Some of the references at the bottom your report are malformed (e.g. Stringr, Httr, Tidyr). These should be able to be fixed in your .bib file. 
- In the README there aren't instructions on using `make clean` 
- Extremely minor, but on your README it says "date: 28/11/2020". I'm not sure what the date refers to and using a standard date format might be more clear than DD/MM/YYYY. 
- I agree with the TA that the transitions between figures in the report could be a bit smoother.

P.S. I noticed that at the end of your group contract it says "subject to chang". Is that a typo or a hilarious reference to Community?

**Comment by rtaph** [comment]
Thanks for the input, @sbabicki ! All seems sensible to me.

And re: Chang, I wish we that clever.

**Comment by ChadNeald** [comment]
Wow going deep into the project and even reading the group contract! An A+ reviewer. Thanks for the feedback @sbabicki!

**Comment by kmoravej** [comment]
Thanks @sbabicki for your comments.

**Comment by yuanxiongbear** [comment]
Thanks @sbabicki for the feedback!

**Comment by rtaph** [comment]
Feedback Implementation

- [x] A link to the EDA
	- See 5ff55f6 in #78
- [x] Fix resolution in tables
	- See 458e78b in #78
- [ ] ~Explore use of colour in main scatterplot~
	- To be addressed in #65
- [ ] Fix formatting of references
- [X] Explain usage of `make clean`
	- See bb3902c4cd3a5057127e0de600d5d7d3e3132716 in #66
- [x] Use ISO date formats  
	-  See c6e19b8 in #76 
- [x] Fix transition between report figures
	-  See 84e992f in #69.
- [x] Correct "subject to chang" in group contract.
	-  See c6e19b8 in #76
