### ISSUE TITLE
Milestone 3 Peer Feedback (Marco)

### ISSUE THREAD

**Issue by mmyz88** [UBC-MDS/bc_election_turnout#62]
Hello Group 19, 

Glad to peer review your project it was really cool. 
Below is my feedback based on tag [`0.2.0`](https://github.com/UBC-MDS/bc_election_turnout/tree/v0.2.0)

- **Documentation**: 
  - It is great. File structure is explicit and well organized. Github workflow is also very well maintained. 
      - P.S. How did you guys get rid of the redundant commits and have only PR's show up in your main repo?? That looks super professional
- **Code**: 
  - Code works. Code is very readable as it is very well modularized. 
- **Analysis and reasoning:** 
  - Analysis is thorough and correct. 
- **Communication**: 
  - Yes, report is very well made and easy to follow. It is also interesting to read the reports in different format. For example, pdf and html offer really different experience.
  - One minor potential improvement - in the Results & Discussion section, the third sentence:
      >  As the p-value p<.001 falls below our alpha threshold...

      This could be misleading to think 0.001 as the alpha value.
- **Suggestions**: 
  - The reference section in README.md seems a bit odd. Not an expert in citation formats, but are the two lines starting with 2018a and 2018b in the right format? (If you guys have made sure this is correct just ignore me)
  - In the Usage section of README.md, could include `make clean` to improve reproducibility
  - Overall, the project milestone is very well done and it was hard for me to spot room for improvement. I am especially impressed by the data cleaning process, as well as the abundant amount of EDA done while maintaining high modularity between the scripts. Great job :)

**Comment by rtaph** [comment]
Thanks for the thoughtful comments, @mmyz88 ! They make sense to me and implementing them will help make our project even better!

Re: your question on redundant commits, we set up main branch protection so that changes could only be folded in via peer-reviewed PRs (disallowed pushes to main). We also turned off merge-commits so that the only way to accept the PR was via "git squash" or "rebase". This meant all intermediate commits inside a PR got "squashed" into one single commit, with the message of that commit being taken from the PR title and the PR ID added. Nifty little trick, right!?

**Comment by rtaph** [comment]
Feedback Implementation

- [ ] Fix references formatting
- [x] Fix language about p-values
- [X] Explain usage of `make clean`
	- Fixed via bb3902c4cd3a5057127e0de600d5d7d3e3132716 in #66

**Comment by ChadNeald** [comment]
I've been trying to fix the references format for both the readme and the report. It looks like the style is to place "-------" when there is a repeated author. So it's not a bug but more of a stylistic choice. That said there is a way to disable this using some combination of the following code but I've had no luck and don't want to spend too much more time on it. If anyone else has any ideas I'm all ears! 
```
# place in references.bib file
@IEEEtranBSTCTL{IEEEexample:BSTcontrol,
  CTLdash_repeated_names = "no"
}
# place in .tex file
\usepackage[redeflists]{IEEEtrantools}

# place in .tex file right after \begin{document}
\bstctlcite{IEEEexample:BSTcontrol}```

**Comment by ChadNeald** [comment]
I've also did a small rewording of the analysis section of the report to make it more clear that our p is < 0.001 and our alpha is 0.05.

**Comment by rtaph** [comment]
The new wording on p-values is A+. I am not bothered by the "-----", so if it is a hassle and a half we can skip it.
